Create Birthday.py
AntonTkachenko53/pycore-group-project pull request #7
Opened 2023-10-14 18:00 UTC by Vasilivi4

class Birthday

2023-10-14 18:15 UTC, kravtsov-s-o requested changes
https://prnt.sc/84DfpgaxeyTj

я бы сказал проверки не работают

2023-10-14 18:15 UTC, kravtsov-s-o commented on personal_assistant_folder/personal_assistant_folder/Birthday.py
> +    def validate_and_normalize(self):
Почти полностью повторяет def validate(self):
один из них явно лишний

2023-10-14 18:53 UTC, Vasilivi4 commented on personal_assistant_folder/personal_assistant_folder/Birthday.py
> +    def validate_and_normalize(self):
Вроде поправил.

2023-10-15 07:16 UTC, closed without merging

2023-10-15 09:32 UTC, AntonTkachenko53 commented on personal_assistant_folder/personal_assistant_folder/Field.py
В цьому файлі  не можна щось видаляти, це базова структура класу, і всі іні наслідувані класи повинні опиратись на нього.
Твої зміни зламають код інших 4-ьох класів, котрі наслідуються від класу Field.
Ти просто перевизначаешь метод def validate(self) для свого класу Birthday.
Необхідно повернути цей файл до базового вигляду